"""initial schema

Revision ID: 0b2f4d5cbeb7
Revises: 
Create Date: 2026-04-12 04:02:56.407232

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b2f4d5cbeb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('routes_total', sa.Integer(), nullable=False),
    sa.Column('routes_success', sa.Integer(), nullable=False),
    sa.Column('routes_failed', sa.Integer(), nullable=False),
    sa.Column('dates_scraped', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('destination_label', sa.String(length=100), nullable=False),
    sa.Column('destinations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('origins', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('days_ahead', sa.Integer(), nullable=False),
    sa.Column('sheet_name_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('special_sheets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('daily_cheapest_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_group_id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('destination', sa.String(length=8), nullable=False),
    sa.Column('depart_date', sa.Date(), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('deep_link', sa.String(length=2048), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_group_id'], ['route_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin', 'destination', 'depart_date')
    )
    op.create_index('ix_daily_cheapest_route_origin_date', 'daily_cheapest_prices', ['route_group_id', 'origin', 'depart_date'], unique=False)
    op.create_table('scrape_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_group_id', sa.UUID(), nullable=True),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('destination', sa.String(length=8), nullable=False),
    sa.Column('depart_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('offers_found', sa.Integer(), nullable=False),
    sa.Column('cheapest_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_group_id'], ['route_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape_logs')
    op.drop_index('ix_daily_cheapest_route_origin_date', table_name='daily_cheapest_prices')
    op.drop_table('daily_cheapest_prices')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('route_groups')
    op.drop_table('collection_runs')
    # ### end Alembic commands ###
